### ISSUE TITLE
About verifier_server compile

### ISSUE THREAD

**Issue by ghcavani** [brunollopes/zkpprotocolkafka#1]
Verifier_server is unable to compile. AuthGrpc, AuthenticationAnswerResponse and other files are missing. Can you help me? thank you

**Comment by brunollopes** [comment]
Hi @ghcavani just saw this now.
Did you managed to solve it ?

**Comment by ghcavani** [comment]
Yes, thank you for your reply. The code was generated with the grpc plug-in.



At 2023-03-06 21:08:45, "brunollopes" ***@***.***> wrote:

Hi @ghcavani just saw this now.
Did you managed to solve it ?

**Comment by ghcavani** [comment]
> 

Yes, thank you for your reply. The code was generated with the grpc plug-in.

**Comment by brunollopes** [comment]
Yes!
